### ISSUE TITLE
Sorgente dati

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/nonportaleregionesicilia#1]
Ciao @cristianolongo ,
la sorgente dati l'hai generata a partire dal foglio elettronico condiviso? 

E per ogni aggiornamento (saranno pochi) di nuovi dati, ripartirai da lì?

Grazie

**Comment by cristianolongo** [comment]
E' necessario scaricare il foglio elettronico condiviso come tsv (csv con separatore tab). Successivamente si crea l'ontologia a partire da questo con lo script csv2dcat.php. L'ontologia va poi arrichita con le inferenze (io uso protege ma qualsiasi reasoner OWL-DL va bene) e caricata su dydra.com.

**Comment by cristianolongo** [comment]
Pare lungo come processo ma richiede se va tutto bene circa 5 minuti. Tra un po aggiungo una sezione "Dati" con i puntatori all'originale, all'ontologia e all'endpoint sparql.

**Comment by aborruso** [comment]
@cristianolongo grazie.

Quindi posso considerare il foglio elettronico come l'attuale sorgente dei dati, in cui verranno inseriti eventuali aggiornamenti?

**Comment by cristianolongo** [comment]
Sicuramente, è la sorgente "primaria".

**Comment by aborruso** [comment]
Grazie
