### ISSUE TITLE
inserire nel database data pubblicazione dell'ultima risorsa

### ISSUE THREAD

**Issue by cirospat** [SiciliaHub/nonportaleregionesicilia#17]
come su Petrusino sarebbe utile per l'utente finale potere visualizzare nella piattaforma del non-portale la data di pubblicazione dell'ultima risorsa, così che alla nuova visita si ha prontezza delle ultime risorse censite da ODS. Quindi inserire nel database la data pubblicazione dell'ultima risorsa.

**Comment by aborruso** [comment]
@cirospat nel db abbiamo già inserito e valorizzato il campo, quindi è cosa abbastanza rapida.
Vediamo se riusciamo in settimana.

Grazie

**Comment by cirospat** [comment]
grazie a te/voi

Il giorno 12 ottobre 2015 14:16, Andrea Borruso <notifications@github.com>
ha scritto:
