### ISSUE TITLE
Aggiornare colonna 'data ultimo aggiornamento'

### ISSUE THREAD

**Issue by marcoalfano** [SiciliaHub/nonportaleregionesicilia#20]
(Per me)
Aggiornare/completare colonna e uniformare le voci.

(Per Andrea)
La inseriamo in home page? C'e' il rischio di creare confusione con 'data di inserimento'?

**Comment by aborruso** [comment]
@marcoalfano e se esponissimo soltanto "ultimo aggiornamento"?

Nel caso di un dato appena inserito corrisponde, ma non mi sembra un gran problema. E' il dato per cui si garantisce l'ultima verifica sul sito sorgente.

Che ne dici?

**Comment by marcoalfano** [comment]
@aborruso l'idea mi sembra buona ;)
In pratica mettiamo sempre la data in cui noi abbiamo caricato o aggiornato il dataset sul non portale indipendentemente da quando è stato creato dalla Regione.
Questo sicuramente ci semplifica le cose.
Ovviamente dovremmo periodicamente verificare se ci sono nuove versioni del dataset.
Ma questo lo dovremmo fare a prescindere.

**Comment by marcoalfano** [comment]
@aborruso Quando puoi modifica in home page 'data inserimento' con 'ultimo aggiornamento'
