### ISSUE TITLE
verifica link social gruppo di lavoro

### ISSUE THREAD

**Issue by giusreale** [SiciliaHub/nonportaleregionesicilia#22]
In molti casi i link ai social (o al profilo) dei membri del gruppo di lavoro sono errati, non so come modificarli altrimenti lo avrei fatto io. 
Questa è la pagina a cui fare riferimento:
http://nonportale.opendatasicilia.it/cosa.html

**Comment by aborruso** [comment]
@giusreale me ne dici uno? Ho fatto click un po' a caso e funzionano

**Comment by giusreale** [comment]
Qusti a me non funzionano: Alessandro Pernice; Davide Taibi; il mio;
Maurizio Foderà e Marco Alfano

Il giorno 14 ottobre 2015 10:39, Andrea Borruso <notifications@github.com>
ha scritto:

**Comment by aborruso** [comment]
Colpa mia :( 

@giusreale mi scrivi il tuo?

**Comment by marcoalfano** [comment]
Mi sembra un problema delle persone che hanno un link a linkedin...anche a me ora da una maschera di accesso mentre prima andava direttamente sul profilo

**Comment by giusreale** [comment]
Per me uno fra questi due.. se ci son problemi con linkedin va benissimo
anche twitter.. Grazie Andrea!

https://it.linkedin.com/in/realegiuseppe

https://twitter.com/gius_reale

2015-10-14 10:51 GMT+02:00 Andrea Borruso <notifications@github.com>:

**Comment by aborruso** [comment]
@giusreale grazie per la segnalazione, Ho corretto il tuo.

Ti ho invitato tra gli editor: la modifica è semplice e si fa in questo modo http://youtu.be/ODzZ5bax6fw?hd=1

A te e @marcoalfano, se recuperate (senza fretta) gli altri indirizzi, chiudiamo questa issue.

@dtaibi ha già corretto.

Saluti

**Comment by giusreale** [comment]
@aborruso più tardi provo a farlo ;-)

Il giorno 14 ottobre 2015 12:15, Andrea Borruso <notifications@github.com>
ha scritto:
