### ISSUE TITLE
Aggiungere Elenco Anagrafe Opere Incompiute

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/nonportaleregionesicilia#30]
http://pti.regione.sicilia.it/portal/page/portal/PIR_PORTALE/PIR_LaStrutturaRegionale/PIR_AssInfrastruttureMobilita/PIR_UfficioSpecialediCoordinamento/PIR_opereincompiute

**Comment by marcoalfano** [comment]
Fatto!

**Comment by aborruso** [comment]
Grazie @marcoalfano (che figata lavorare così e che figata github)

**Comment by marcoalfano** [comment]
:) :)
