### ISSUE TITLE
Aggiungere dataset Beni immobili e gestione patrimonio

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/nonportaleregionesicilia#31]
E' un sottoinsieme di amministrazione trasparente, ma penso che meriti di avere uno spazio autonomo.

URL: [http://pti.regione.sicilia.it/portal/page/portal/PIR_PORTALE/PIR_LaStrutturaRegionale/PIR_AssBeniCulturali/PIR_BeniCulturaliAmbientali/PIR_Amministrazionetrasparente/PIR_Beniimmobiliegestionepatrimonio](http://pti.regione.sicilia.it/portal/page/portal/PIR_PORTALE/PIR_LaStrutturaRegionale/PIR_AssBeniCulturali/PIR_BeniCulturaliAmbientali/PIR_Amministrazionetrasparente/PIR_Beniimmobiliegestionepatrimonio)

**Comment by marcoalfano** [comment]
Fatto!
