### ISSUE TITLE
Creare pagina portali regionali

### ISSUE THREAD

**Issue by marcoalfano** [SiciliaHub/nonportaleregionesicilia#35]
A partire dal foglio 'portali regionali' dello spreadsheet si deve creare una nuova pagina del non-portale che contenga la lista dei portali.
In particolare deve contenere il nome (con il link al portale) e l'ufficio titolare e deve essere filtrabile tramite la tematica.

**Comment by marcoalfano** [comment]
@aborruso ho creato un motore di ricerca customizzato google che cerca su tutti i portali regionali (e solo su quelli).
Ti ho aggiunto come amministratore e trovi il motore all'indirizzo https://cse.google.com/cse/setup/basic?cx=016814764579831695142:ljtnagdxutu
Ho etichettato tutti i siti con il tema di dati.gov.it che usiamo per il non-portale e quando faccio una ricerca mi fornisce i risultati su tutti i siti o quelli più significativi per le singole etichette (ho limitato il numero di etichette da mostrare a 5 ma si può variare).
L'ho rivisto con Davide e mi sembra che funzioni abbastanza bene (prova ad es. ad inserire 'bandi').
Lo aggiungerei al non-portale. A questo punto però la pagina dei portali regionali verrebbe superata da quella di questo motorre che potrebbe stare in una pagina sua con tutte le spiegazioni del caso.
Ovviamente il motore può essere modificato/ampliato.
Che dici?

**Comment by aborruso** [comment]
2016-06-15 12:45 GMT+02:00 Marco Alfano <notifications@github.com>:

> Lo aggiungerei al non-portale. A questo punto però la pagina dei portali
> regionali verrebbe superata da quella di questo motorre che potrebbe stare
> in una pagina sua con tutte le spiegazioni del caso.
> Ovviamente il motore può essere modificato/ampliato.
>

Marco mi piace molto, complimenti.

Una cosa così va bene http://nonportale.opendatasicilia.it/cerca.html ??


-- 
 Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

--

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by marcoalfano** [comment]
Grazie!
Mi sembra ottimo ;)
Purtroppo il bottoncino 'cerca' (con la lente di ingrandimento) non si vede ma questo credo sia un problema di google. Me lo da anche con un altro cse.
Aggiungo un pò di testo esplicativo nella pagina.
Il tab 'cerca' va poi aggiunto nei menu delle altre pagine del non-portale.

**Comment by aborruso** [comment]
Aggiunto il menu "Cerca nei siti" in tutte le pagine
