### ISSUE TITLE
Aggiungere testo descrittivo nella pagina "Cerca nei siti"

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/nonportaleregionesicilia#47]
@marcoalfano aggiungerei [qui](https://github.com/SiciliaHub/nonportaleregionesicilia/blob/gh-pages/cerca.html#L92) un testo descrittivo brevissimo sul cosa è questa pagina.

Se sei d'accordo però pensaci tu, che ne sei l'ideatore

**Comment by marcoalfano** [comment]
@aborruso testo aggiunto ;) vedi se ti sembra che va bene e se no, modificalo pure o dimmi se devo aggiungere altre info.

**Comment by aborruso** [comment]
Ho fatto una piccola modifica. Metterei in link alla tabella che contiene l'elenco degli URL mappati. Che ne dici?

**Comment by marcoalfano** [comment]
Ottimo! Sono d'accordo per il link (all'inizio l'idea era quella di creare la pagina dei siti regionali, vedi #35). L'unico timore era che poi veniva simile a quella dei dataset e questo poteva confondere. Mi sembra che con il link questo pericolo non ci sia...

**Comment by aborruso** [comment]
@marcoalfano dove trovo una tabella con l'elenco di link? Mi avrai già inviato un gdrive, ma non riesco a recuperarlo. Grazie

**Comment by marcoalfano** [comment]
@aborruso è nel quarto foglio del google sheet del non-portale https://docs.google.com/spreadsheets/d/15cFU9v2x3ACb1IPcVE9Xg3wc5fuay8NAYDXQnoMcOFw/edit#gid=2118198704

**Comment by aborruso** [comment]
Ho aggiunto il link all'elenco dei siti mappati dal motore
