### ISSUE TITLE
Migliorare il foglio di stile del form della pagina "cerca nei siti"

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/nonportaleregionesicilia#48]

**Comment by aborruso** [comment]
@marcoalfano ho sistemato lo stile, inserendo il codice che trovi [qui](https://github.com/SiciliaHub/nonportaleregionesicilia/blob/gh-pages/css/style.css#L70)

Se aggiorni la pagina dovresti vedere tutto bene. Fanne uso per l'altro sito di cui mi dicevi

**Comment by marcoalfano** [comment]
Okk, grazie!
