### ISSUE TITLE
Aggiungere nello spreadsheet id assessorato/dipartimento

### ISSUE THREAD

**Issue by marcoalfano** [SiciliaHub/nonportaleregionesicilia#7]
(per me)

due colonne:
1) codice IPA
2) codice univoco ufficio

**Comment by aborruso** [comment]
@marcoalfano per me ok

**Comment by marcoalfano** [comment]
@aborruso Le due nuove colonne andrebbero dopo la colonna "Assessorato/Dipartimento" perché si riferiscono a questa colonna. Le posso aggiungere là o le devo mettere al'ultimo?

**Comment by aborruso** [comment]
@marcoalfano mettile momentaneamente in fondo, anche vuote, con il nome di campo che hai scelto.

Non appena hai fatto, scrivimelo, io faccio poi una modifica e ti do il via per procedere

**Comment by marcoalfano** [comment]
@aborruso Fatto! Grazie ;)

**Comment by aborruso** [comment]
Puoi procedere!
